"""add_user_id

Revision ID: c11b06fec4a0
Revises: 001_initial
Create Date: 2026-08-27 20:00:04.658099

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c11b06fec4a0'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('user_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_slug'), table_name='transcripts')
    op.create_index('ix_transcripts_slug', 'transcripts', ['slug'], unique=False)
    op.create_unique_constraint('transcripts_slug_key', 'transcripts', ['slug'])
    op.create_index('ix_transcript_chunks_embedding_hnsw', 'transcript_chunks', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_column('sessions', 'user_id')
    # ### end Alembic commands ###
